### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by 777Prabhjot** [Vijaykv5/foodvilla#2]
In mobile screens navbar is not taking full width also i think cards need box shadow in mobile screen view and search input also have layout issues.

**Screen Shot**
<img width="207" alt="Screenshot 2023-04-18 151738" src="https://user-images.githubusercontent.com/68184118/232740464-13bcf697-fc18-4fc1-82f0-ebc9adf11c44.png">

### **I would love to contribute can i**

**Comment by Vijaykv5** [comment]
I Actually Didn't work on Responsiveness 
Yeah you can work on :)
