### ISSUE TITLE
Cards items are not center

### ISSUE THREAD

**Issue by 777Prabhjot** [Vijaykv5/foodvilla#3]
Cards items needs to be in center and also i think footer should not be fixed it's not a good user experience and as u can see in the screenshot after inserting value in search input it's not visible so i think it needs a border.

**Screen Shot**
<img width="946" alt="Screenshot 2023-04-18 152307" src="https://user-images.githubusercontent.com/68184118/232741773-c9396061-d37d-4c07-9c98-c035b1db99be.png">

<img width="893" alt="Screenshot 2023-04-18 152434" src="https://user-images.githubusercontent.com/68184118/232741813-e8c9f86b-67e6-4efc-8618-c02811e4fee3.png">

### **I would love to work on this can i**

**Comment by Vijaykv5** [comment]
Actually when I'm fixing , at the bottom , Its not working fixing well in other pages.
Yeah you can definitely try ..
